version: '2'

services:
  application:
    build:
      dockerfile: Dockerfile
    container_name: marvel-app
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres14-container:5432/marvel-catalog-db
      - SPRING_DATASOURCE_USERNAME=marvel-catalog-user
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - postgres_database

  postgres_database:
    image: postgres:14-alpine
    container_name: postgres14-container
#    ports:
#      - '5432:5432'
    environment:
      - POSTGRES_USER=marvel-catalog-user
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=marvel-catalog-db
